// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Book = 1,
  Chapter = 2,
  Label = 3,
  Section = 4,
  Language = 5,
  Content = 6,
  Text = 7,
  Reference = 8,
  Italic = 9,
  Bold = 10,
  Doubt = 11,
  Glossary = 12,
  Gloss = 13,
  Term = 14,
  Annotation = 15,
  Note = 16
