// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'UOQOPOOOVOPO'#C^OOOO'#Cm'#CmQQOPOOO[OPO,58xOOOO-E6k-E6kOOOO'#Cn'#CnOaOPO1G.dOOOO-E6l-E6lOiOPO'#C`OOOO'#Co'#CoOnOPO7+$OO[OPO,58zOOOO-E6m-E6mOyOPO1G.fO!ROPO'#CaOOOO'#Cp'#CpO!WOPO7+$QO[OPO,58{OOOO-E6n-E6nO[OPO'#ChO[OPO'#CkOOOO<<Gl<<GlO!lOPO<<GlO#]OQO1G.gO#dOPO,59SO#lOPO,59VOOOOAN=WAN=WOOOO'#Cq'#CqO#tOQO'#CbO$_OPO7+$RO$vOPO'#CiOOOO'#Cr'#CrO${OPO1G.nO%^OPO'#ClOOOO'#Ct'#CtO%cOPO1G.qOOOO-E6o-E6oO%qOPO<<GmOOOO'#Cs'#CsO&YOPO,59TOOOO-E6p-E6pO&nOSO,59WOOOO-E6r-E6rOOOO-E6q-E6qO&sOQO1G.rOOOO7+$^7+$^",
  stateData: "&{~OjPO~ORSO~OkUO~OkUOlXO~OR[O~OlXOiQqjQq~OkUOm_O~ORbO~Om_OndOpeOiSqjSqlSq~OpeOiSyjSylSy~OVlOWlOXlOYlOZlO~OkUO~P!zOkUOooO~OkUOorO~OiUXjUXkUXlUXmUXnUXpUX~P!zOkUOiTqjTqlTqmTqnTqpTq~O^wO~OooOi[ij[il[ip[i~ORzO~OorOi_ij_il_i~OkUOiTyjTylTymTynTypTy~O^wOi]aj]al]ao]ap]a~Oq}O~OV!OO~OVk~",
  goto: "#riPPjPnrvPPPPPy|P!Q!W![!b!|#S#Y#`#f#lTQORTYVZT`^aRnhRgaTpiqQfaRkgTsjtQRORTRQVS[WV^hijvQ^[QhbQidQjeRvnQZVR]ZQa^RcaQmhRumQqiRyqQxoR|xQtjR{t",
  nodeNames: "⚠ Book Chapter Label Section Language Content Text Reference Italic Bold Doubt Glossary Gloss Term Annotation Note",
  maxTerm: 33,
  skippedNodes: [0],
  repeatNodeCount: 8,
  tokenData: "0d~R}OX$OXY$yYZ%pZ^$y^p$Opq$yqs$Ost&itu$Ouv'bvz$Oz{'m{!Q$O!Q![)a![!_$O!_!`*g!`!a,]!a!c$O!c!})a!}#Q$O#Q#R,b#R#S,|#S#T$O#T#o)a#o#p.p#p#q$O#r#y$O#y#z$y#z$f$O$f$g$y$g#BY$O#BY#BZ$y#BZ$IS$O$IS$I_$y$I_$I|$O$I|$JO$y$JO$JT$O$JT$JU$y$JU$KV$O$KV$KW$y$KW&FU$O&FU&FV$y&FV;'S$O;'S;=`$s<%lO$OQ$TYVQOs$Otu$Ovz$O{!_$O!a#Q$O#S#o$O#p#q$O#r;'S$O;'S;=`$s<%lO$OQ$vP;=`<%l$OU%QYqSVQOs$Otu$Ovz$O{!_$O!a#Q$O#S#o$O#p#q$O#r;'S$O;'S;=`$s<%lO$OV%yYqSVQkROs$Otu$Ovz$O{!_$O!a#Q$O#S#o$O#p#q$O#r;'S$O;'S;=`$s<%lO$O~&lQpq&rst&w~&wOj~~&zQpq'Qst'V~'VOl~~'YPpq']~'bOm~~'ePuv'h~'mOp~~'pYOs(`tu(`vz(`{!_(`!a#Q(`#S#o(`#p#q(`#r;'S(`;'S;=`)Z<%lO(`~(cZOs(`tu(`vz(`z{)U{!_(`!a#Q(`#S#o(`#p#q(`#r;'S(`;'S;=`)Z<%lO(`~)ZOY~~)^P;=`<%l(`R)h_RPVQOs$Otu$Ovz$O{!Q$O!Q![)a![!_$O!a!c$O!c!})a!}#Q$O#S#T$O#T#o)a#p#q$O#r;'S$O;'S;=`$s<%lO$O~*jZOs+]tu+]vz+]{!_+]!_!`,W!a#Q+]#S#o+]#p#q+]#r;'S+];'S;=`,Q<%lO+]~+bY^~Os+]tu+]vz+]{!_+]!a#Q+]#S#o+]#p#q+]#r;'S+];'S;=`,Q<%lO+]~,TP;=`<%l+]~,]On~~,bOo~~,eR!Q![,n!c!},n#T#o,n~,sRW~!Q![,n!c!},n#T#o,n~-PYOs-otu-ovz-o{!_-o!a#Q-o#S#o-o#p#q-o#r;'S-o;'S;=`.j<%lO-o~-rZOs-otu-ovz-o{!_-o!a#Q-o#R#S.e#S#o-o#p#q-o#r;'S-o;'S;=`.j<%lO-o~.jOX~~.mP;=`<%l-o~.sYOs/ctu/cvz/c{!_/c!a#Q/c#S#o/c#p#q/c#r;'S/c;'S;=`0^<%lO/c~/fZOs/ctu/cvz/c{!_/c!a#Q/c#S#o/c#p#q/c#q#r0X#r;'S/c;'S;=`0^<%lO/c~0^OZ~~0aP;=`<%l/c",
  tokenizers: [0, 1, 2],
  topRules: {"Book":[0,1]},
  tokenPrec: 270
})
